config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:index]
  get 'users/:username', to: 'users#show', as: 'user'
  post 'users/:username', to: 'users#like', as: 'like_user'

  resources :repos, only: [:index]
  get 'repos/:reponame', to: 'repos#show', as: 'repo'
  post 'repos/:reponame', to: 'repos#like', as: 'like_repo'

  get '', to: 'repos#show', as: 'welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  validates_uniqueness_of :user_id, :scope => "name"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :likes

  def liked?(name)
    likes.where(name: name).first.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def check_rate_of_limit(parsed_resp)
    if parsed_resp['message']
      render 'source/client_error', locals: { message: parsed_resp['message'] }
      false
    else
      true
    end
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :authenticate_user!, only: :like

  def index
    params['name'] ||= 'trailblazer'
    url = Github.search('repositories', params['name'])
    response = HTTParty.get(url)
    @repos = response.parsed_response
  end

  def show
    params['reponame'] ||= 'trailblazer/trailblazer'
    url = Github.show('repos', params['reponame'])
    response = HTTParty.get(url)
    @repo = response.parsed_response
    if check_rate_of_limit(@repo)
      @repo['contributors'] = HTTParty.get(@repo['contributors_url']+"?#{Github.envs}").parsed_response
      @likes = Like.where(name: params['reponame'])
    end
  end

  def like
    current_user.likes.create(name: params['reponame'])
    @likes = Like.where(name: params['reponame'])
    render partial: 'likes/likes'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :like

  def index
    params['name'] ||= 'trailblazer'
    url = Github.search('users', params['name'])
    response = HTTParty.get(url)
    @users = response.parsed_response
  end

  def show
    url = Github.show('users', params['username'])
    @user = HTTParty.get(url).parsed_response
    if check_rate_of_limit(@user)
      @user['user_repos'] = HTTParty.get(@user['repos_url']+"?#{Github.envs}").parsed_response
      @likes = Like.all.where(name: params['username'])
    end
  end

  def like
    current_user.likes.create(name: params['username'])
    @likes = Like.where(name: params['username'])
    render partial: 'likes/likes'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Github Client</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'source/header' %>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Github Client</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'source/header' %>
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <!-- <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p> -->
          <% if alert %>
            <div class="alert alert-danger">
              <strong>Alert!</strong><%= alert %>
            </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/likes/_likes.html.erb
<%= @likes.count %>
<span class="glyphicon glyphicon-thumbs-up green">

app/views/repos/index.html.erb
<% if @repos['errors'].present? %>
  <%= @repos['errors'] %>
<% elsif @repos['items'].empty? %>
  No results for <%= params['name'] %>
<% else %>
  <% @repos['items'].each do |repo| %>
    <h3>
      <span class="glyphicon glyphicon-folder-open">
      <%= link_to repo['name'], repo_path([repo['owner']['login'], repo['name']]) %><br>
    </h3>
    <div style="color: #767676">
      <%= repo['description'] %>
    </div>
    <div style="color: #767676; font-size: 12px">
      <%= repo['language'] %>
    </div>
    <hr width='50%' align='left'>
  <% end %>
<% end %>

app/views/repos/show.html.erb
<div style="font-size:700%">
  <%= @repo['name'].capitalize %>
  <%= link_to @repo['html_url'] do %>
    <svg aria-hidden="true" class="octicon octicon-mark-github" height="50" version="1.1" viewBox="0 0 16 16" width="50"><path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path></svg>
  <% end %>
</div>
<p>
  Owner <%= link_to @repo['owner']['login'], user_path(@repo['owner']['login']) %><br>
  <%= @repo['description'] %>
</p>
<div class="likes">
  <%= @likes.count %>
  <% if user_signed_in? %>
    <% unless current_user.liked? @repo['full_name'] %>
      <%= link_to like_repo_path(@repo['full_name']), method: :post, class: 'like', remote: true  do %>
        <span class="glyphicon glyphicon-thumbs-up">
      <% end %>
    <% else %>
      <span class="glyphicon glyphicon-thumbs-up green">
    <% end %>
  <% end %>
</div>
<div class="container">
  <div class="row">
    <h2>Contributors:</h2>
    <% @repo['contributors'].each do |contributor| %>
      <div class="col-lg-1 col-md-1 col-sm-2 col-xs-3">
        <%= link_to user_path(contributor['login']) do %>
          <%= image_tag(contributor['avatar_url']+'&s=100', style: 'max-width: 100px', title: contributor['login']) %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/source/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Github Client', welcome_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li <% if controller_name == 'users' %>class="active"<% end %>><%= link_to 'Users', users_path %></li>
        <li <% if controller_name == 'repos' %>class="active"<% end %>><%= link_to 'Repos', repos_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Log in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>

      <% if controller_name == 'users' || controller_name == 'repos' %>
        <%= form_tag("/#{controller_name}", method: "get", class: 'navbar-form navbar-right') do %>
        <div class="form-group">
          <%= text_field_tag :name, '', class: 'form-control', placeholder: "Search for #{controller_name}..." %>
        </div>
          <%= submit_tag "Search", class: 'btn btn-default' %>
        <% end %>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/source/client_error.erb
<h1>
  Oooops, something gone wrong...
</h1>
<p><%= message %></p>

app/views/users/index.html.erb
<% if @users['errors'].present? %>
  <%= @users['errors'] %>
<% elsif @users['items'].empty? %>
  No results for <%= params['name'] %>
<% else %>
<div class="container">
  <div class="row">
    <% @users['items'].each do |user| %>
      <div class="col-lg-1 col-md-1 col-sm-2 col-xs-3">
        <%= link_to user_path(user['login']) do %>
          <%= image_tag(user['avatar_url']+'&s=100', style: 'max-width: 100px', title: user['login']) %>
        <% end %>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div style="font-size:700%">
  @<%= @user['login'] %>
  <%= link_to @user['html_url'] do %>
    <svg aria-hidden="true" class="octicon octicon-mark-github" height="50" version="1.1" viewBox="0 0 16 16" width="50"><path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path></svg>
  <% end %>
</div>
<div class="likes">
  <%= @likes.count %>
  <% if user_signed_in? %>
    <% unless current_user.liked? @user['login'] %>
      <%= link_to like_user_path(@user['login']), method: :post, class: 'like', remote: true  do %>
        <span class="glyphicon glyphicon-thumbs-up">
      <% end %>
    <% else %>
      <span class="glyphicon glyphicon-thumbs-up green">
    <% end %>
  <% end %>
</div>

<p><%= @user['bio'] %></p>
<%= image_tag(@user['avatar_url']+'&s=200', style: 'max-width: 200px') %><br>
<% @user['user_repos'].each do |repo| %>
  <%= link_to repo['name'], repo_path([repo['owner']['login'], repo['name']]) %><br>
<% end %>